name: Release npm package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm lint
      - run: npm run build
      - run: npm sematic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTION }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
